<a href="https://colab.research.google.com/github/shaliha223/DSA_class_activities/blob/main/numpy_and_pandas_Assignment_Shaliha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [ ]:
A = np.arange(10,50)
A1 = np.reshape(A,(4,10))

print("A=",A)
print(" Reshaped matrix=",A1)
print("last column of the reshaped matrix=",A1[:,-1])

A= [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 Reshaped matrix= [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
last column of the reshaped matrix= [19 29 39 49]


2. Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [ ]:
B = np.full((3,3), 5)
B1 = np.random.randint(1,9,(3,3))

Add = np.add(B,B1)
multiply =np.multiply(B,B1)
T = np.transpose(Add)
T1 = multiply.T


print(B)
print(B1)
print("B+B1=",Add)
print("B*B1",multiply)
print("Transpose of B+B1",T)
print("Transpose of B*B1",T1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1 3 8]
 [7 3 2]
 [2 1 3]]
B+B1= [[ 6  8 13]
 [12  8  7]
 [ 7  6  8]]
B*B1 [[ 5 15 40]
 [35 15 10]
 [10  5 15]]
Transpose of B+B1 [[ 6 12  7]
 [ 8  8  6]
 [13  7  8]]
Transpose of B*B1 [[ 5 35 10]
 [15 15  5]
 [40 10 15]]


3. Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.

In [ ]:
C = np.random.randint(10,100,size=(15))
print(C)
Condition = C>50
C[Condition]=-1
print(C)
print(np.sum(Condition))

[77 83 67 97 89 83 80 89 84 51 96 10 59 35 79]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 10 -1 35 -1]
13


4. Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row

In [ ]:
D = np.random.random((5,4))
D1 = np.sum(D,axis=1)
max = np.max(D1)
row_idx = np.argmax(D1)
D2 = D[ row_idx:]

print("matrix=",D)
print("sum of each row=",D1)
print("maximum row sum=",max)
print("index of the max sum row=",row_idx)
print("row which have max sum=",D2)

matrix= [[0.74153194 0.71710269 0.32519514 0.70032471]
 [0.57888385 0.61673062 0.29781093 0.37048151]
 [0.78625727 0.98984333 0.15624638 0.71306973]
 [0.40183484 0.00930672 0.90170223 0.91562019]
 [0.72321809 0.92124405 0.88679734 0.80432806]]
sum of each row= [2.48415449 1.8639069  2.64541671 2.22846397 3.33558755]
maximum row sum= 3.3355875457385347
index of the max sum row= 4
row which have max sum= [[0.72321809 0.92124405 0.88679734 0.80432806]]


In [ ]:
a = np.max(D,axis=1,keepdims=True)
b = np.min(D,axis=1,keepdims=True)
D_norm = (D - b)/(a - b)

print(D_norm)

[[1.         0.94132336 0.         0.9010243 ]
 [0.8813282  1.         0.         0.22786485]
 [0.75577398 1.         0.         0.66797671]
 [0.43310414 0.         0.98464332 1.        ]
 [0.         1.         0.8260495  0.40959262]]


5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [ ]:
E = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
uniques, counts = np.unique(E, return_counts=True)

print("unique=",uniques)
print("elements that appear more than once",uniques[counts>1])

unique= [1 3 5 7 9]
elements that appear more than once [1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.


In [ ]:
F = np.random.randint(1,36,(6,6))
F1 = F[1:5,1:5]
F2 = F1[F1 % 2 == 0]


print(F)
print("middle 4x4 matrix=",F1)
print("even numbers=",F2)

[[ 5 11 12 27 13 21]
 [28 31 32 29 32  1]
 [14 12 16 22 13  9]
 [ 2  7  2 18 24 11]
 [26  6 15 29 11 11]
 [35 26 12 23 24 12]]
middle 4x4 matrix= [[31 32 29 32]
 [12 16 22 13]
 [ 7  2 18 24]
 [ 6 15 29 11]]
even numbers= [32 32 12 16 22  2 18 24  6]


7. Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)

In [ ]:
G = np.arange(12).reshape(3, 4)
G1 = np.reshape(G,(2,6))
G2 = G1.flatten()
G3 = G2.reshape(4,3)

print("matrix =", G)
print("reshaped matrix=", G1)
print("flatten array=", G2)
print("again reshaped array=", G3)

matrix = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped matrix= [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
flatten array= [ 0  1  2  3  4  5  6  7  8  9 10 11]
again reshaped array= [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8 . Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]
● Then append a new column [7, 8, 9]

In [ ]:
a = np.array([[1, 2], [3, 4]])
a = np.append(a, [[5,6]], axis=0)
a = np.append(a, [[7],[8],[9]], axis=1)

print(a)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined_array = np.concatenate((a, b, c))
print("Joined array:", joined_array)

reshaped_matrix = joined_array.reshape(3, 3)
print("Reshaped 3x3 matrix:\n", reshaped_matrix)

diagonal_elements = np.diag(reshaped_matrix)
print("Diagonal elements:", diagonal_elements)

Joined array: [1 2 3 4 5 6 7 8 9]
Reshaped 3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal elements: [1 5 9]


10. Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.
● Count how many such values exist

In [ ]:
H = np.arange(1, 21)
print("Array", H)

divisible = H[(H % 3 == 0) | (H % 5 == 0)]
print("\nValues divisible by 3 or 5:\n", divisible)

count = divisible.size
print("Count of values divisible by 3 or 5:", count)

Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20]
Count of values divisible by 3 or 5: 9


#ASIGNMENT 2

1. Load the Titanic dataset and display the first 10 rows.


In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

2. Find the number of missing values in each column.

In [4]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

3. Find the percentage of passengers who survived, grouped by gender.

In [6]:
survived_rate = df.groupby('sex')['survived'].mean()
print(survived_rate)

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64


4. Find the average, median, and standard deviation of passenger ages.

In [8]:
a = df['age'].mean()
b = df['age'].median()
c = df['age'].std()

print("mean of age:", a)
print("median of age",b)
print("std of age",c)

mean of age: 29.69911764705882
median of age 28.0
std of age 14.526497332334044


5. Count how many passengers were in each class (pclass).

In [10]:
d = df['pclass'].value_counts()

print("Passenger count per class:", d)

Passenger count per class: pclass
3    491
1    216
2    184
Name: count, dtype: int64


6. Show all passengers who were female, under age 18, and survived.

In [14]:
e = df[(df['sex']=='female') & (df['age']< 18) & (df['survived']==1)]
display(e)

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

7. Replace missing age values with the median age.

In [15]:
df['age'].fillna(b,inplace=True)

In [16]:
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

8. Create a column age_group with values:
a. 'Child' for age < 18
b. 'Adult' for age 18–60
c. 'Senior' for age > 60
d. Use: apply() or np.where() or custom function

In [17]:
df['age_group'] = np.where(df['age'] < 18, 'Child',
                   np.where(df['age'] <= 60, 'Adult', 'Senior'))
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  28.0      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

9. Display the top 5 passengers who paid the highest fare

In [19]:
f = df.sort_values(by="fare", ascending=False).head(5)

display(f)

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

10. Find the average fare paid, grouped by both pclass and sex

In [22]:
g = df.groupby(["pclass", "sex"])["fare"].mean()
print(g)


pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


11. Rename the following columns:
a. 'sex' → 'gender'
b. 'fare' → 'ticket_fare'

In [24]:
df = df.rename(columns={"sex": "gender", "fare": "ticket_fare"})

df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'ticket_fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'age_group'],
      dtype='object')

12. Count the number of passengers who survived and didn’t survive, grouped by class.


In [31]:
h =df.groupby(['pclass', 'survived']).size()

print(h)

pclass  survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64


13. Find the average age of passengers grouped by both class and gender.

In [32]:
i = df.groupby(['class', 'gender'])['age'].mean()

print(i)

class   gender
First   female    33.978723
        male      38.995246
Second  female    28.703947
        male      30.512315
Third   female    23.572917
        male      26.911873
Name: age, dtype: float64


/tmp/ipython-input-3174349827.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  i = df.groupby(['class', 'gender'])['age'].mean()
